---
- name: Configura aplicação no Nginx
  template:
    src: rails_app.conf.j2
    dest: /etc/nginx/sites-available/{{ app_name }}

- name: Linka sites-enabled com sites-available
  file:
    src: /etc/nginx/sites-available/{{ app_name }}
    dest: /etc/nginx/sites-enabled/{{ app_name }}
    state: link

- name: Reinicializa puma
  systemd: name=puma.{{ app_name }}.service state=reloaded 

- name: Reinicializa Nginx
  systemd: name=nginx state=reloaded
  