---
- name: Bloqueia porta tcp do acesso externo
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ puma.tcp_port }}"
    jump: DROP
  become: true

- name: Bloqueia porta ssl do acesso externo
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ puma.ssl_port }}"
    jump: DROP
  become: true

- name: Libera porta tcp para o localhost
  iptables:
    chain: INPUT
    protocol: tcp
    source: localhost
    destination_port: "{{ puma.tcp_port }}"
    jump: ACCEPT
  become: true

- name: Libera porta ssl pro localhost
  iptables:
    chain: INPUT
    protocol: tcp
    source: localhost
    destination_port: "{{ puma.ssl_port }}"
    jump: ACCEPT
  become: true