---
- name: Seta configuração do puma.rb
  template:
    src: puma.rb.j2
    dest: /var/www/{{app_name}}/config/puma.rb

- name: Remove o force SSL
  lineinfile:
    dest: /var/www/{{ app_name }}/config/environments/production.rb
    regexp: '^config.force_ssl = true'
    line: 'config.force_ssl = false'
    backrefs: yes
  become: true
  
- name: Criar pasta compartilhada
  file:
    path: "{{ item }}"
    state: directory
  with_items:
   - /var/www/{{ app_name }}/shared/pids
   - /var/www/{{ app_name }}/shared/sockets
   - /var/www/{{ app_name }}/shared/log

- name: Cria o puma como serviço
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.{{ app_name }}.service

- name: Recarrega o systemd e inicia o puma
  systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: puma.{{ app_name }}.service

# - import_tasks: iptables.yml 




