---
- name: Instala certbot
  apt:
    name: certbot
    state: present
  become: true

- name: Verifica se o certificado SSL existe
  stat:
    path: /etc/letsencrypt/live/{{ nginx.domain }}/privkey.pem
  register: ssl_cert
  
- name: Configura certificados SSL's
  command: "certbot certonly --webroot -w /var/www/{{ app_name }}/public -d {{ nginx.domain }} -d www.{{ nginx.domain }} --agree-tos -m {{ email_from }}"
  when: not ssl_cert.stat.exists

- name: Seta configuração do puma.rb
  template:
    src: puma.rb.j2
    dest: /var/www/{{app_name}}/config/puma.rb

- name: Adiciona force SSL
  lineinfile:
    dest: /var/www/{{ app_name }}/config/environments/production.rb
    regexp: 'config.force_ssl = false'
    line: 'config.force_ssl = true'
    backrefs: yes
  become: true

- name: Configura aplicação no Nginx
  template:
    src: rails_app.conf.j2
    dest: /etc/nginx/sites-available/{{ app_name }}
  
- name: Reinicializa puma
  systemd: name=puma.{{ app_name }}.service state=reloaded 

- name: Reinicializa Nginx
  systemd: name=nginx state=reloaded
  
- import_tasks: iptables.yml 

